Recherche de jeunes dans une strucutre Milo
SocialGouv/pass-emploi-web pull request #1071
Opened 2023-09-26 06:47 UTC by Mzem

2023-09-26 08:19 UTC, arthurlbrjc requested changes

2023-09-26 08:19 UTC, arthurlbrjc commented on pages/agenda/sessions/[session_id].tsx
>      conseiller.agence.id,
`conseiller.agence.id` -> `conseiller.structureMilo.id` ?
Et modifier la ligne 593 > `if (!conseiller?.structureMilo?.id) return { notFound: true }`

2023-09-26 08:21 UTC, Mzem commented on services/jeunes.service.ts
> +  page?: number
elle sera utilisée plus tard
cette route remplace rechercherJeuneByEtablissement et getJeunes

2023-09-26 08:24 UTC, arthurlbrjc requested changes

2023-09-26 08:24 UTC, arthurlbrjc commented on services/jeunes.service.ts
> +export async function getJeunesDeLaStructureMilo(
À utiliser aussi dans la page `EditionRdv` à la place de `getJeunesDeLEtablissementClientSide` ? (**uniquement** pour le conseiller Milo)

2023-09-26 08:26 UTC, arthurlbrjc commented on services/jeunes.service.ts
> +  page?: number
On le rajoutera plus tard alors.

2023-09-26 08:36 UTC, elba-octo commented on services/jeunes.service.ts
> +export async function getJeunesDeLaStructureMilo(
```suggestion
export async function getBeneficiairesDeLaStructureMilo(
```
?

2023-09-26 08:36 UTC, elba-octo commented on services/jeunes.service.ts
> +  page?: number
yagniii

2023-09-26 08:58 UTC, elba-octo commented on services/jeunes.service.ts
> +  return {
mettre un try/catch

2023-09-26 09:14 UTC, elba-octo commented on services/jeunes.service.ts
> +  return {
on ne peut pas afficher la page de détail d'une session

2023-09-26 11:06 UTC, Mzem commented on services/jeunes.service.ts
> +export async function getJeunesDeLaStructureMilo(
pour l'instant non (ça peut créer des confusions avec la logique des etablissements qui est toujours en place pour les AC)
plus tard oui

2023-09-26 11:06 UTC, Mzem commented on services/jeunes.service.ts
> +export async function getJeunesDeLaStructureMilo(
ok

2023-09-26 11:06 UTC, Mzem commented on services/jeunes.service.ts
> +  return {
pas compris le on ne peut pas afficher la page de détail d'une session
pourquoi un try catch spécifiquement ici ?

2023-09-26 14:46 UTC, Mzem commented on services/jeunes.service.ts
> +  return {
??

2023-09-27 08:29 UTC, Mzem commented
merci @elba-octo @arthurlbrjc pour les retours
j'en prendrai compte demain (en plus de la code smell)

2023-09-29 14:41 UTC, Mzem commented on services/jeunes.service.ts
> +  return {
pas de 404 possible ici, tableau vide si aucun bénéficiaire

2023-09-29 14:42 UTC, Mzem commented on services/jeunes.service.ts
> +  return {
c'est testé E2E sur la review app (par contre l'inscription ne marche pas et c'est temporairement à cause de l'API MILO en question qui est down)

2023-10-02 09:53 UTC, merged