feat: (us-277) dernière activité d'un jeune
SocialGouv/pass-emploi-web pull request #128
Opened 2022-01-26 16:26 UTC by sanh-sandra

feat: Ajout de la colonne dernière activité d'un jeune dans la page Mes Jeunes

2022-01-26 16:43 UTC, arthurlbrjc requested changes

2022-01-26 16:43 UTC, arthurlbrjc commented on pages/mes-jeunes/index.tsx
> +                    ? todayOrDate(new Date(jeune.lastActivity))
On peut enlever le ternaire nan, vu que `lastActivity` est obligatoire.

2022-01-26 16:43 UTC, arthurlbrjc commented on tests/jestDateMock.ts
> +export const onBeforeEach = (): void => {
Pourquoi ne pas utiliser plutôt spécifiquement `jest.useFakeTimers` (et `jest.setSystemTime`) ?

2022-01-26 16:43 UTC, arthurlbrjc commented on tests/utils/date.test.ts
> +      const isToday = dateIsYesterday(new Date('2018-12-30T23:59:59.000Z'))
`isYesterday` ?

2022-01-26 16:43 UTC, arthurlbrjc commented on utils/date.ts
> +  const yesterday = new Date(today)
Pourquoi pas juste `const yesterday = new Date()` ?

2022-01-26 16:43 UTC, arthurlbrjc commented on utils/date.ts
> +  yesterday.setDate(yesterday.getDate() - 1)
Ça wrap automatiquement en début de mois au mois précédent ?

2022-01-27 09:51 UTC, sanh-sandra commented on pages/mes-jeunes/index.tsx
> +                    ? todayOrDate(new Date(jeune.lastActivity))
les anciens jeunes n'ont pas de lastActivity :/ Mais tous les nouveaux en auront

2022-01-27 09:51 UTC, sanh-sandra commented on utils/date.ts
> +  yesterday.setDate(yesterday.getDate() - 1)
yes 😊

2022-01-27 10:07 UTC, arthurlbrjc commented on tests/utils/date.test.ts
> +    jest.setSystemTime(new Date('2018-12-31T23:59:59.000Z'))
Je pense qu'il vaut mieux le mettre dans le scope d'un test.  
Ou alors carrément dans le `beforeEach` du fichier.

2022-01-27 10:14 UTC, merged