Feat us 376 nb actions non terminees jeunes
SocialGouv/pass-emploi-web pull request #190
Opened 2022-03-04 10:24 UTC by sanh-sandra

feat: Ajout d'une nouvelle colonne dans le tableau des jeunes pour afficher le nombre d'actions non terminées par jeune. 

- [ ] Tri par ordre croissant/décroissant de la colonne
- [ ] MAJ de l'interface jeune
- [ ] Matomo
- [ ] Test

2022-03-04 11:27 UTC, arthurlbrjc requested changes

2022-03-04 11:27 UTC, arthurlbrjc commented on components/jeune/TableauJeunes.tsx
> +        jeune2.nbActionsNonTerminees = jeune2.nbActionsNonTerminees || 0
Techniquement on a toujours un `nbActionsNonTerminees`, c'est plutôt un problème de typage je pense.

2022-03-04 11:27 UTC, arthurlbrjc commented on interfaces/jeune.ts
> +  nbActionsNonTerminees?: number
Je l'aurais pas mis dans l'interface `Jeune` mais uniquement dans `TableauDesJeunes`.
Genre
```ts
interface JeuneAvecInfosComplementaires extends Jeune {
  messagesNonLus: number
  nbActionsNonTerminees: number
}
```
(et du coup on peut supprimer `JeunesAvecMessagesNonLus`)

2022-03-04 11:27 UTC, arthurlbrjc commented on interfaces/jeune.ts
> +  nbActionsNonTerminees?: number
Ah mais c'est chiant parce `nbActionsNonTerminees` est renseignée côté SSR et `messagesNonLus` côté front... ><

2022-03-04 11:27 UTC, arthurlbrjc commented on interfaces/jeune.ts
> +  nbActionsNonTerminees?: number
En tout cas j'aurais pas mis l'info des `nbActions` dans l'interface `Jeune` qui est utilisée partout :thinking:  
Du coup je ferais un type `JeuneAvecNbActionsNonTerminees` dans les props du `TableauJeunes`
```ts
type JeuneAvecNbActionsNonTerminees = Jeune & { nbActionsNonTerminees: number }
```
puis un type `JeuneAvecInfosComplementaires` dans le state
```ts
type JeuneAvecInfosComplementaires = JeuneAvecNbActionsNonTerminees & { messagesNonLus: number }
```

2022-03-04 11:27 UTC, arthurlbrjc commented on pages/mes-jeunes/index.tsx
> +    )
`.find` plutôt que `.filter`  
Et du coup
```ts
if (!currentJeuneAction) jeune.nbActionsNonTerminees = 0
else jeune.nbActionsNonTerminees = currentJeuneAction.inProgressActionsCount + currentJeuneAction.todoActionsCount
```

2022-03-04 11:27 UTC, arthurlbrjc commented on pages/mes-jeunes/index.tsx
> +  })
Il manque un `return jeune` à la fin de l'intérieure du `map` je pense.

2022-03-04 11:27 UTC, arthurlbrjc commented on tailwind.config.js
> +      table: '1fr 1fr 1fr 1fr',
`repeat(4, 1fr)` ?

2022-03-04 11:28 UTC, arthurlbrjc commented on pages/mes-jeunes/index.tsx
> +  })
Cf -> https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=190&id=SocialGouv_pass-emploi-web&open=AX9UePniM1GCx48qJLQ2

2022-03-04 13:45 UTC, sanh-sandra commented on pages/mes-jeunes/index.tsx
> +  })
j'ai corrifé en remplaçant par un forEach

2022-03-04 14:58 UTC, elba-octo approved these changes

2022-03-04 15:24 UTC, arthurlbrjc commented on components/jeune/TableauJeunes.tsx
> +      jeune2: JeuneAvecInfosComplementaires & { messagesNonLus: number }
`JeuneAvecInfosComplementaires` tout court nan ?

2022-03-04 15:24 UTC, arthurlbrjc commented on pages/mes-jeunes/index.tsx
> +    jeunesAvecNbActionsNonTerminees.push(jeuneAvecNbActionsNonTerminees)
`forEach + push` => `map`

2022-03-07 08:44 UTC, arthurlbrjc approved these changes

2022-03-07 08:56 UTC, merged