Feat/us 838 liste des favoris
SocialGouv/pass-emploi-web pull request #446
Opened 2022-08-02 14:34 UTC by walidOcto

- [x] redirection vers page favoris du jeune
- [x] gestion des tabs
- [x] liste des favoris du jeune dans un tableau
- [x] liste des recherches du jeune dans un tableau
- [x] service favoris/offres
- [x] service favoris/recherches
- [x] test offres
- [x] test recherches
- [x] test service
- [x] fil ariane 
- [x] matomo
- [x] conditioner l'acces a l'affichage de la liste des favoris  
- [x] style
- [x] imports par package
- [x] TODO à fixer/supprimer

2022-08-03 15:12 UTC, elba-octo commented on components/favoris/offres/OffreRow.tsx
> +      className='table-row h-20 text-sm rounded-[6px] shadow-s hover:bg-primary_lighten group'
pas de besoin de fixer la hauteur
```suggestion
      className='table-row text-sm rounded-[6px] shadow-s hover:bg-primary_lighten group'
```

2022-08-03 15:26 UTC, elba-octo commented on components/favoris/offres/OffresList.tsx
> +const OffresList = ({ offres }: FavorisListProps) => {
```suggestion
const TableauOffres = ({ offres }: FavorisListProps) => {
```
comme il s'agit bien d'un tableau. ou OffresTableau, sur le projet on a plutôt tendance à mettre en préfixe

2022-08-03 15:27 UTC, elba-octo commented on components/favoris/recherches/OngletRecherches.tsx
> +      <RecherchesList recherches={recherches} />
```suggestion
      <TableauRecherches recherches={recherches} />
```

2022-08-03 15:32 UTC, elba-octo commented on fixtures/favoris.ts
> +export function uneListeDOffres() {
on peut typer la fixture. On a tendance à mettre en Partial<Type>  et se donner la possibilité d'écraser la fixture par défaut pour manipuler à la volée dans nos tests.
```suggestion
export function uneListeDOffres = (overrides: Partial<Offre> = {)}: Offre => {
``

2022-08-03 15:33 UTC, elba-octo commented on fixtures/services.ts
> +    getRecherches: jest.fn(),
nitpick 
```suggestion
    getRecherches: jest.fn(),
```
```suggestion
    getRecherchesSauvegardees: jest.fn(),
```

2022-08-03 15:40 UTC, elba-octo commented on pages/mes-jeunes/[jeune_id]/favoris.tsx
> +  const favorisService = withDependance<FavorisService>('favorisService')
nitpick:
remonter, ordre de déclaration:
session
dépendances/services
appels/récupération props

2022-08-03 15:41 UTC, elba-octo commented on tests/pages/Favoris.page.test.tsx
> +      it('rediriges vers la page d’accueil', async () => {
```suggestion
      it('redirige vers la page d’accueil', async () => {
```

2022-08-03 15:42 UTC, elba-octo commented on tests/pages/Favoris.page.test.tsx
> +    it('affiche la liste de ses offres', () => {
```suggestion
    it('affiche la liste des offres du jeune', () => {
```
nitpick: ses? à qui?

2022-08-03 15:45 UTC, elba-octo commented on pages/mes-jeunes/[jeune_id]/favoris.tsx
> +    if (error instanceof ApiError && error.status === 403) {
qu'est-ce qui vous a poussé à le faire ici?
(pour rester homogène on gère la logique de try/catch côté service.)

2022-08-03 15:56 UTC, adgeg commented on components/favoris/offres/OffreRow.tsx
> +      className='table-row h-20 text-sm rounded-[6px] shadow-s hover:bg-primary_lighten group'
En fait, on veut que quelque soit la longueur du titre, on ait une cellule d'au moins 80 px. C'est la contrainte de la maquette. Tu vois une autre manière de faire ?

2022-08-03 15:59 UTC, adgeg commented on tests/pages/Favoris.page.test.tsx
> +    it('affiche la liste de ses offres', () => {
A oui, au début j'avais mis un describe `pour un jeune donné`, mais @arthurlbrjc m'a dit de l'enlever à juste titre. Mais je n'ai pas mis à jour le nom du test…

2022-08-03 16:30 UTC, arthurlbrjc requested changes

2022-08-03 16:30 UTC, arthurlbrjc commented on components/favoris/offres/OffresList.tsx
> +                <div className='mb-2' />
Ça peut pas être fait avec un `border-spacing-y-2` plutôt ?

2022-08-03 16:30 UTC, arthurlbrjc commented on components/favoris/offres/OngletOffres.tsx
> +    <>
Pas besoin du fragment du coup.

2022-08-03 16:30 UTC, arthurlbrjc commented on components/favoris/recherches/OngletRecherches.tsx
> +    <>
Idem, pas besoin du fragment.

2022-08-03 16:30 UTC, arthurlbrjc commented on components/favoris/recherches/RechercheRow.tsx
> +export default function RechercheRow({ recherche }: { recherche: Recherche }) {
Même commentaires que dans `OffreRow`.

2022-08-03 16:30 UTC, arthurlbrjc commented on components/favoris/recherches/RecherchesList.tsx
> +const RecherchesList = ({ recherches }: RecherchesListProps) => {
Même commentaire que dans `OffresList`

2022-08-03 16:30 UTC, arthurlbrjc commented on components/favoris/recherches/RecherchesList.tsx
> +              <HeaderCell label='Lieu/ localisation' />
L'espacement avec le `/` est chelou nan ?

2022-08-03 16:30 UTC, arthurlbrjc commented on fixtures/favoris.ts
> +export function uneListeDOffres() {
Pour les listes on rend rarement les fixtures customisables.

2022-08-03 16:30 UTC, arthurlbrjc commented on interfaces/favoris.ts
> +}
Ces `enum` ne sont pas utiles. On n'a pas la main sur les valeurs et il n'y a pas de logique qui y est liée.

2022-08-03 16:30 UTC, arthurlbrjc commented on interfaces/json/favoris.ts
> +}
Idem, ces `enum` apportent une fausse sécurité.  
Ce qu'il faudrait plutôt c'est des méthodes `jsonToTypeOffre` et `jsonToTypeRecherche` avec un switch/case et gestion des cas incohérents. Comme ce qui est fait par exemple dans _jsonToActionStatus_ (mais sans l'enum)

2022-08-03 16:30 UTC, arthurlbrjc commented on components/favoris/offres/OngletOffres.tsx
> +export function OngletOffres({ offres }: OngletOffresProps) {
Ce composant est pas indispensable et n'apporte pas grand chose. On peut directement utiliser `<OffresList>` dans la page.

2022-08-03 16:30 UTC, arthurlbrjc commented on components/favoris/recherches/OngletRecherches.tsx
> +export function OngletRecherches({ recherches }: OngletRecherchesProps) {
Ce composant est pas indispensable et n'apporte pas grand chose. On peut directement utiliser `<RecherchesList>` dans la page.

2022-08-03 16:30 UTC, arthurlbrjc commented on pages/mes-jeunes/[jeune_id]/favoris.tsx
> +          className='mt-8 pb-8 border-b border-primary_lighten'
Je vois pas cette border dans la maquette :thinking:

2022-08-03 16:30 UTC, arthurlbrjc commented on pages/mes-jeunes/[jeune_id]/favoris.tsx
> +  }
Je pense pas que ce soit indispensable ça. Next va router vers cette page que si y'a un `[jeune_id]`, sinon on arrivera jamais ici.

2022-08-03 16:30 UTC, arthurlbrjc commented on pages/mes-jeunes/[jeune_id]/favoris.tsx
> +  }
À mettre dans le `try` je pense.

2022-08-03 16:30 UTC, arthurlbrjc commented on tests/pages/Favoris.page.test.tsx
> +        ;(withDependance as jest.Mock).mockReturnValue(favorisService)
Pas besoin de ça quand la session est invalide parce qu'on passe dans un `return` avant d'avoir besoin de la dépendance.

2022-08-03 16:30 UTC, arthurlbrjc commented on tests/pages/Favoris.page.test.tsx
> +            user: { id: 'id-conseiller', structure: 'MILO' },
Pas besoin de mocker ça je pense, c'est pas utilisé dans l'implem.

2022-08-03 16:30 UTC, arthurlbrjc commented on tests/pages/Favoris.page.test.tsx
> +            user: { id: 'id-conseiller', structure: 'MILO' },
Idem, pas besoin de mocker ça.

2022-08-03 16:30 UTC, arthurlbrjc commented on tests/pages/Favoris.page.test.tsx
> +            destination: '/mes-jeunes',
On pourrait éventullement rediriger vers la fiche du jeune ?

2022-08-03 16:34 UTC, arthurlbrjc commented on components/favoris/offres/OffreRow.tsx
> +      className='table-row h-20 text-sm rounded-[6px] shadow-s hover:bg-primary_lighten group'
Dans ce cas, soit :
- c'est un `min-height` plutôt qu'une `height`
- on peut truncate/ellispe le titre pour qu'il soit tout le temps sur une seule ligne

2022-08-04 07:35 UTC, adgeg commented on tests/pages/Favoris.page.test.tsx
> +            destination: '/mes-jeunes',
On en a parlé hier ensemble, tu m'avais dit que ça t'allait. Sachant que je ne sais déjà pas pourquoi on gère ce cas perso…

2022-08-04 07:50 UTC, elba-octo commented on fixtures/favoris.ts
> +export function uneListeDOffres() {
mais on peut typer!

2022-08-04 07:53 UTC, elba-octo commented on components/favoris/offres/OffreRow.tsx
> +      className='table-row h-20 text-sm rounded-[6px] shadow-s hover:bg-primary_lighten group'
pour la valeur de rounded, le 5px reste pertinent et valable pour plusieurs éléments, soit demander si on modifie la valeur, soit on en ajoute une.

2022-08-04 13:03 UTC, elba-octo commented on components/favoris/offres/OffresList.tsx
> +                <div className='mb-2' />
non ça ne fonctionnait pas il y avait déjà des tests sur le sujet la dernière fois quand ActionRow a été implémenté, on avait opté pour la div avec margin

2022-08-04 15:24 UTC, arthurlbrjc approved these changes

2022-08-04 15:31 UTC, merged