fix: fix 404 on index page
SocialGouv/pass-emploi-web pull request #802
Opened 2023-03-20 16:27 UTC by walidOcto

2023-03-21 13:21 UTC, arthurlbrjc reviewed
Est-ce qu'une meilleure solution serait pas de virer le `/index` au moment du login. Il me semble que ça devrait marcher les query-params directement sur la racine `/`.

2023-03-21 13:21 UTC, arthurlbrjc commented on next.config.js
> +        destination: '/',
Attention ça casse les quelques endroits où on teste "/index".

2023-03-21 13:27 UTC, walidOcto commented on next.config.js
> +        destination: '/',
je vais essayer ta solution : /?query_param=value

2023-03-22 08:41 UTC, arthurlbrjc requested changes

2023-03-22 08:41 UTC, arthurlbrjc commented on pages/login.tsx
> +          ? '/?' + new URLSearchParams({ redirectUrl })
Ça casse les endroits où on vérifie la redirection depuis la home/login (`referer.split('?')[0].endsWith('/index')`). Faut qu'on jette un oeil à ça du coup.

2023-03-22 09:59 UTC, merged