feat(us-1699): suggestions conseillers reaffectation
SocialGouv/pass-emploi-web pull request #931
Opened 2023-06-22 12:51 UTC by octo-theg

2023-06-23 13:10 UTC, elba-octo commented on pages/etablissement/reaffectation.tsx
> +            {Boolean(conseillerInitialError) && (
tu peux utiliser le composant `InputError`

2023-06-23 13:10 UTC, elba-octo commented on pages/etablissement/reaffectation.tsx
>              <>
l'apprence du tableau des bénéficiaires est à faire évoluer. Le ticket est peut-être pas assez explicite non plus, ou je ne sais pas si validé et donc faire dans un autre ticket -> à valider avec métier/design:
 - si les informations de conseiller précédent/e-mail conseiller précedent sont pertinentes (pour l'e-mail je pense mais ça dépend aussi de la disponibilité).
A date on ne remonte rien.
Et la coche "tout sélectionner" devient explicite et visible

2023-06-23 13:35 UTC, octo-theg commented on pages/etablissement/reaffectation.tsx
> +      const conseillerAssocie = rechercheConseillerEtablissementParID(
C'est la correspondance entre le conseiller dans _conseillersOptions_ et _conseillersEtablissement_. Je n'ai pas trouvé de terme pour expliciter ça :/

2023-06-26 08:45 UTC, arthurlbrjc requested changes

2023-06-26 08:45 UTC, arthurlbrjc commented on services/conseiller.service.ts
> +    }
On fait ça quand on récupère un élément unique et qu'on veut pas casser en cas d'erreur de l'API.
Là pour le coup on devrait soit ne pas catcher l'erreur soit renvoyer `[]`

2023-06-26 08:45 UTC, arthurlbrjc commented on services/jeunes.service.ts
> +  return getJeunesDuConseillerServerSide(idConseiller, session!.accessToken)
Extraire le code commun aux méthodes client-side et server-side dans une méthode non-exportée (`getJeunesDuConseiller`)

2023-06-26 08:45 UTC, arthurlbrjc commented on pages/etablissement/reaffectation.tsx
> +  const [isRechercheBeneficiairesEnabled, setRechercheBeneficiairesEnabled] =
Ça aurait été cool de faire le renommage _jeune_ -> _beneficiaire_ à un autre moment (autre branche ou au moins autre commit) parce que ça brouille un peu la MR.

2023-06-27 15:24 UTC, arthurlbrjc approved these changes

2023-06-28 08:31 UTC, arthurlbrjc commented on pages/etablissement/reaffectation.tsx
> +      setConseillerInitialError('Aucun conseiller ne correspond')
Traité dans une PR suivante

2023-06-28 08:32 UTC, arthurlbrjc commented on pages/etablissement/reaffectation.tsx
>          <Etape numero={2} titre='Recherchez un portefeuille de bénéficiaires'>
Traité dans une PR suivante

2023-06-28 08:33 UTC, arthurlbrjc commented on pages/etablissement/reaffectation.tsx
> +                label='Rechercher les bénéficiaires'
Traité dans une PR suivante

2023-06-28 08:34 UTC, arthurlbrjc commented on pages/etablissement/reaffectation.tsx
> +                style={ButtonStyle.PRIMARY}
Traité dans une PR suivante

2023-06-28 08:35 UTC, arthurlbrjc commented on pages/etablissement/reaffectation.tsx
>              <>
Traité dans une PR suivante

2023-06-28 09:27 UTC, merged